# Generated by Django 3.2 on 2021-06-11 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.IntegerField(null=True)),
                ('rest_password', models.CharField(default=False, max_length=20)),
                ('rest_email', models.EmailField(default=False, max_length=254)),
                ('rest_image', models.ImageField(upload_to='restaurent_images/')),
                ('rest_type', models.CharField(max_length=10, null=True)),
                ('rest_status', models.CharField(max_length=10, null=True)),
                ('rest_city', models.CharField(max_length=20, null=True)),
                ('rest_state', models.CharField(max_length=20, null=True)),
                ('rest_pincode', models.IntegerField(default=False)),
                ('rest_address', models.CharField(default=False, max_length=50)),
                ('rest_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
