# Generated by Django 3.2 on 2021-06-12 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restarent_app', '0004_alter_restaurentmodel_rest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentmodel',
            name='rest_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurentmodel',
            name='rest_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
