# Generated by Django 3.2 on 2021-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0006_addfoodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentmodel',
            name='rest_ratings',
            field=models.CharField(default=2.5, max_length=3, null=True),
        ),
    ]
