# Generated by Django 3.2 on 2021-06-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0010_oredrmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oredrmodel',
            name='pro',
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='dcat',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='dname',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='dprice',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='dtype',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='oid',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oredrmodel',
            name='rname',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
