# Generated by Django 3.2 on 2021-06-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0012_promosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosmodel',
            name='prome_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='promosmodel',
            name='promo_discription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
