# Generated by Django 3.2 on 2021-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0013_auto_20210629_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosmodel',
            name='promo_code',
            field=models.CharField(max_length=20),
        ),
    ]
