# Generated by Django 3.2 on 2021-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0014_alter_promosmodel_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurentmodel',
            name='rest_type',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
