# Generated by Django 3.2 on 2021-06-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0015_alter_restaurentmodel_rest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addfoodmodel',
            name='image4',
        ),
    ]
