# Generated by Django 3.2 on 2021-07-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0016_remove_addfoodmodel_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
