# Generated by Django 3.2 on 2021-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarent_app', '0017_addtocartmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oredrmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
