# Generated by Django 3.2 on 2021-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20210608_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeatils',
            old_name='gender',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='userdeatils',
            name='status',
        ),
        migrations.AddField(
            model_name='userdeatils',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
