# Generated by Django 3.2 on 2021-06-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_auto_20210610_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeatils',
            name='type',
        ),
    ]
