# Generated by Django 3.2 on 2021-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_remove_userdeatils_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeatils',
            name='login_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
